# Generated by Django 3.1.5 on 2021-01-15 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LappUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, max_length=254)),
                ('lastname', models.CharField(db_index=True, max_length=254)),
                ('profilePic', models.URLField(blank=True, null=True, verbose_name='Profile picture url')),
                ('emailId', models.EmailField(db_index=True, max_length=254)),
                ('contactNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('alterContactNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('street1', models.CharField(max_length=254)),
                ('street2', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('state', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=254)),
                ('zip_pin', models.CharField(max_length=254)),
                ('DOB', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('qualification', models.CharField(max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=50)),
                ('isInstractor', models.BooleanField(default=False, verbose_name='Is this user an instractor')),
                ('isContentAdmin', models.BooleanField(default=False, verbose_name='Is this user a content admin')),
                ('isLearner', models.BooleanField(default=True, verbose_name='Is this user a learner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
